import express from 'express';
import cors from 'cors';
import mongoose from 'mongoose';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';

import Alert from './models/Alert.js';
import TrafficLog from './models/TrafficLog.js';
import User from './models/User.js';
import { verifyToken, checkRole, JWT_SECRET } from './middleware/auth.js';

const app = express();
const PORT = process.env.PORT || 5000;
const MONGODB_URI = 'mongodb://127.0.0.1:27017/aws_monitor';

app.use(cors());
app.use(express.json());

// --- Database Connection ---
mongoose.connect(MONGODB_URI)
  .then(async () => {
    console.log('🚀 Đã kết nối MongoDB thành công!');
    await seedDatabase();
  })
  .catch(err => console.error('❌ Lỗi kết nối MongoDB:', err));

// --- Tự động bơm dữ liệu giả (Seeding) ---
async function seedDatabase() {
  try {
    // 1. Seed Users (Tạo 4 tài khoản test nếu chưa có)
    const userCount = await User.countDocuments();
    if (userCount === 0) {
      const salt = await bcrypt.genSalt(10);
      const hashedPassword = await bcrypt.hash('123456', salt);
      const defaultUsers = [
        { username: 'netadmin', password: hashedPassword, role: 'NetAdmin', fullName: 'Network Administrator' },
        { username: 'secops', password: hashedPassword, role: 'SecOps', fullName: 'Security Operator' },
        { username: 'manager', password: hashedPassword, role: 'Manager', fullName: 'Project Manager' },
        { username: 'admin', password: hashedPassword, role: 'SystemAdmin', fullName: 'System Administrator' }
      ];
      await User.insertMany(defaultUsers);
      console.log('✅ Đã tạo 4 tài khoản Demo (netadmin, secops, manager, admin) với mật khẩu: 123456');
    }

    // 2. Seed Alerts & Traffic
    const alertCount = await Alert.countDocuments();
    if (alertCount === 0) {
      console.log('📦 Đang khởi tạo dữ liệu mẫu phân tích...');
      const mockAlerts = [
        { alert_type: "Brute Force Attack", severity: "High", message: "Multiple failed SSH login attempts detected", source_ip: "192.168.1.105", geo_location: { lat: 35.8617, lng: 104.1954, country: 'China' }, status: 'New' },
        { alert_type: "Port Scanning", severity: "Medium", message: "Sequential port scanning activity observed", source_ip: "10.0.0.54", geo_location: { lat: 55.3781, lng: -3.4360, country: 'UK' }, status: 'In Progress' },
        { alert_type: "Unusual Data Transfer", severity: "High", message: "Large volume sent to unknown external IP", source_ip: "172.16.0.12", geo_location: { lat: 61.5240, lng: 105.3188, country: 'Russia' }, status: 'New' },
        { alert_type: "Malware Communication", severity: "High", message: "Connection to malicious C&C server blocked", source_ip: "192.168.1.200", geo_location: { lat: 37.0902, lng: -95.7129, country: 'USA' }, status: 'Resolved' },
        { alert_type: "DDoS Attempt", severity: "High", message: "High frequency requests causing resource exhaustion", source_ip: "45.22.11.1", geo_location: { lat: -23.5505, lng: -46.6333, country: 'Brazil' }, status: 'New' },
        { alert_type: "Unauthorized Access", severity: "Low", message: "Login attempt outside business hours", source_ip: "10.0.1.25", geo_location: { lat: -25.2744, lng: 133.7751, country: 'Australia' }, status: 'False Positive' }
      ];
      for (const a of mockAlerts) {
        a.timestamp = new Date(Date.now() - Math.floor(Math.random() * 7 * 24 * 60 * 60 * 1000));
        a.audit_logs = [{ action: 'Alert Generated by GuardDuty AI', user: 'System' }];
      }
      await Alert.insertMany(mockAlerts);

      const mockTraffic = [];
      const protocols = ['TCP', 'TCP', 'TCP', 'HTTP', 'HTTPS', 'UDP', 'ICMP'];
      const now = Date.now();
      for(let i = 0; i < 200; i++) {
        const timeOffset = Math.floor(Math.random() * 7 * 24 * 60 * 60 * 1000); 
        mockTraffic.push({
          timestamp: new Date(now - timeOffset),
          source_ip: `10.0.${Math.floor(Math.random()*255)}.${Math.floor(Math.random()*255)}`,
          destination_ip: `192.168.1.${Math.floor(Math.random()*50)}`,
          bytes_sent: Math.floor(Math.random() * 500) + 10, 
          bytes_received: Math.floor(Math.random() * 400) + 10,
          protocol: protocols[Math.floor(Math.random() * protocols.length)],
          port: Math.floor(Math.random() * 8000) + 80
        });
      }
      await TrafficLog.insertMany(mockTraffic);
    }
  } catch (err) {
    console.error('Lỗi khi seed data:', err);
  }
}


// =========================================================================
// API AUTHENTICATION
// =========================================================================
app.post('/api/auth/login', async (req, res) => {
  try {
    const { username, password } = req.body;
    const user = await User.findOne({ username });
    if (!user) return res.status(404).json({ error: "Tài khoản không tồn tại" });

    const isMatch = await bcrypt.compare(password, user.password);
    if (!isMatch) return res.status(400).json({ error: "Mật khẩu không chính xác" });

    const token = jwt.sign({ id: user._id, username: user.username, role: user.role }, JWT_SECRET, { expiresIn: '1d' });
    res.json({ token, user: { username: user.username, role: user.role, fullName: user.fullName } });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});


// =========================================================================
// PROTECTED API ENDPOINTS (Yêu cầu JWT Token)
// =========================================================================

app.get('/api/dashboard/overview', verifyToken, async (req, res) => {
  try {
    const alertCount = await Alert.countDocuments();
    const trafficStats = await TrafficLog.aggregate([
      { $group: { _id: null, totalSent: { $sum: "$bytes_sent" }, totalReceived: { $sum: "$bytes_received" } } }
    ]);
    const totalBytes = trafficStats.length > 0 ? (trafficStats[0].totalSent + trafficStats[0].totalReceived) : 0;
    res.json({ totalTrafficGb: (totalBytes / 1024).toFixed(2), guardDutyAlerts: alertCount, lookoutAnomalies: Math.floor(alertCount / 2) });
  } catch (error) { res.status(500).json({ error: error.message }); }
});

app.get('/api/dashboard/traffic', verifyToken, async (req, res) => {
  try {
    const mockData = [
      { time: '10:00', sent: 210, received: 150 }, { time: '11:00', sent: 260, received: 190 },
      { time: '12:00', sent: 420, received: 340 }, { time: '13:00', sent: 370, received: 290 },
      { time: '14:00', sent: 510, received: 430 }, { time: '15:00', sent: 320, received: 230 }
    ];
    res.json(mockData);
  } catch (error) { res.status(500).json({ error: error.message }); }
});

app.get('/api/security/alerts', verifyToken, async (req, res) => {
  try {
    const alerts = await Alert.find().sort({ timestamp: -1 }).limit(10);
    res.json(alerts);
  } catch (error) { res.status(500).json({ error: error.message }); }
});

app.get('/api/dashboard/map', verifyToken, async (req, res) => {
  try {
    const alerts = await Alert.find({ "geo_location.lat": { $exists: true } }).limit(50);
    res.json(alerts);
  } catch (error) { res.status(500).json({ error: error.message }); }
});

app.get('/api/dashboard/protocols', verifyToken, async (req, res) => {
  try {
    const protocolStats = await TrafficLog.aggregate([
      { $group: { _id: "$protocol", count: { $sum: 1 } } }
    ]);
    const formatted = protocolStats.map(item => ({ name: item._id, value: item.count }));
    res.json(formatted);
  } catch (error) { res.status(500).json({ error: error.message }); }
});

app.get('/api/infrastructure/health', verifyToken, (req, res) => {
  res.json({
    cpu_usage: Math.floor(Math.random() * 40) + 20, 
    mem_usage: Math.floor(Math.random() * 30) + 40, 
    disk_usage: Math.floor(Math.random() * 20) + 60,
    status: 'Healthy'
  });
});

app.get('/api/dashboard/anomaly', verifyToken, (req, res) => {
  const data = [];
  let base = 200;
  for(let i=0; i<10; i++) {
    const forecast = base + Math.random()*50;
    const actual = i === 7 ? forecast + 250 : forecast + (Math.random()*40 - 20);
    data.push({
      time: `1${i}:00`,
      forecast: Math.round(forecast),
      actual: Math.round(actual),
      isAnomaly: actual > forecast + 100
    });
  }
  res.json(data);
});

app.get('/api/traffic/top-ips', verifyToken, async (req, res) => {
  try {
    const { protocol } = req.query;
    const matchStage = protocol && protocol !== 'ALL' ? { $match: { protocol } } : { $match: {} };
    
    const topIps = await TrafficLog.aggregate([
      matchStage,
      { $group: { _id: "$source_ip", total_bytes: { $sum: "$bytes_sent" } } },
      { $sort: { total_bytes: -1 } },
      { $limit: 10 }
    ]);
    
    const formatted = topIps.map(item => ({ ip: item._id, bytes: item.total_bytes }));
    res.json(formatted);
  } catch(error) {
    res.status(500).json({ error: error.message });
  }
});


// =========================================================================
// ROLE-BASED ENDPOINTS (Yêu cầu cả Token lẫn Quyền Hệ thống)
// =========================================================================

// Yêu cầu Role phải là SecOps hoặc SystemAdmin mới được đổi trạng thái cảnh báo
app.put('/api/security/alerts/:id/status', verifyToken, checkRole(['SecOps', 'SystemAdmin']), async (req, res) => {
  try {
    const { status } = req.body;
    const user = req.user.username; // Lấy từ Token
    const alert = await Alert.findById(req.params.id);
    if(!alert) return res.status(404).json({ error: "Alert not found" });
    
    alert.status = status;
    alert.audit_logs.push({ action: `Status changed to ${status}`, user: user });
    await alert.save();
    
    res.json(alert);
  } catch (error) { res.status(500).json({ error: error.message }); }
});

app.listen(PORT, () => {
  console.log(`Backend Server đang chạy tại http://localhost:${PORT}`);
});
